# Generated by Django 5.0.7 on 2024-07-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='sinopse',
            new_name='resume',
        ),
    ]
